### ISSUE TITLE
FHIR deployment revision

### ISSUE THREAD

**Issue by gmej** [Gravitate-Health/hapi-fhir-jpaserver-starter-ips#2]
I think it would be good to review the deployment of both FHIR server deployments (ePI R5 and IPS R4). FHIR is highly configurable and we may be ignoring some interesting options, and we might discover some misconfigurations. It would be good if someone at Trifork or HL7 could review it. @jkiddo @joofio What do you think about this?

**Comment by joofio** [comment]
the config file is here in this repo?

**Comment by gmej** [comment]
Yes:
- [application.yaml](https://github.com/Gravitate-Health/hapi-fhir-jpaserver-starter-ips/blob/2768779ca9ca6c28b8b186732f474b0eb47a5343/src/main/resources/application.yaml)
- [Helm configuration values.yaml](https://github.com/Gravitate-Health/hapi-fhir-jpaserver-starter-ips/blob/2768779ca9ca6c28b8b186732f474b0eb47a5343/charts/hapi-fhir-jpaserver/values.yaml)

The same files in the same path are present in the other fhir ePI repo

**Comment by joofio** [comment]
couldnt you benefit from a external database like postgres?

**Comment by gmej** [comment]
It's currently using postgres with an independent deployment.

**Comment by gmej** [comment]
I didn't see this. It is using postgres. The application.yaml has defined internal database but the flag enabled is set to false. It uses external postgres deployment. 

I'm closing this issue as now we are using the official image, and configuration is passed to customize our server.
Deployment is moved to https://github.com/Gravitate-Health/hapi-fhir-deployments
